global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:9464"]

  - job_name: lms-services-metrics
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - /etc/prometheus/services-targets.json

  - job_name: lms-services-health
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - /etc/prometheus/services-health-targets.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
