version: '3.9'

services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: lms-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - ./services/services-targets.json:/etc/prometheus/services-targets.json:ro
      - ./services/services-health-targets.json:/etc/prometheus/services-health-targets.json:ro
    ports:
      - '9090:9090'
    depends_on:
      - otel-collector
      - blackbox-exporter

  loki:
    image: grafana/loki:3.1.1
    container_name: lms-loki
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./config/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
    ports:
      - '3100:3100'

  tempo:
    image: grafana/tempo:2.5.0
    container_name: lms-tempo
    command: ["-config.file=/etc/tempo/tempo.yml"]
    volumes:
      - ./config/tempo/tempo.yml:/etc/tempo/tempo.yml:ro
    ports:
      - '3200:3200'
      - '4317:4317'
      - '4318:4318'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.106.1
    container_name: lms-otel-collector
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - ./config/otel/otel-collector.yml:/etc/otel-collector.yml:ro
    ports:
      - '9464:9464'
      - '4319:4317'
      - '4320:4318'
    depends_on:
      - loki
      - tempo

  promtail:
    image: grafana/promtail:3.1.1
    container_name: lms-promtail
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./config/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/log:/var/log:ro
    depends_on:
      - loki

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: lms-blackbox
    command: ["--config.file=/etc/blackbox/blackbox.yml"]
    volumes:
      - ./config/blackbox/blackbox.yml:/etc/blackbox/blackbox.yml:ro
    ports:
      - '9115:9115'

  grafana:
    image: grafana/grafana:11.1.4
    container_name: lms-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
      - loki
      - tempo
