FROM node:20-alpine

ARG SERVICE_PATH
WORKDIR /app

COPY ${SERVICE_PATH}/package*.json ./
RUN npm install
COPY ${SERVICE_PATH}/ ./
COPY infrastructure/deployment/scripts/start-service.sh /usr/local/bin/start-service.sh
RUN chmod +x /usr/local/bin/start-service.sh

EXPOSE 8000
ENTRYPOINT ["/usr/local/bin/start-service.sh"]
