from __future__ import annotations

from typing import Protocol

from .models import (
    AuthorizationDecisionLog,
    PermissionDefinition,
    PolicyRule,
    RoleDefinition,
    SubjectRoleAssignment,
)


class RBACStorage(Protocol):
    def create_role(self, role: RoleDefinition) -> RoleDefinition: ...
    def list_roles(self, tenant_id: str) -> list[RoleDefinition]: ...
    def get_role(self, tenant_id: str, role_id: str) -> RoleDefinition | None: ...
    def update_role(self, role: RoleDefinition) -> RoleDefinition: ...
    def list_permissions(self) -> list[PermissionDefinition]: ...
    def put_role_permissions(self, tenant_id: str, role_id: str, permission_keys: list[str]) -> None: ...
    def get_role_permissions(self, tenant_id: str, role_id: str) -> list[str]: ...
    def create_assignment(self, assignment: SubjectRoleAssignment) -> SubjectRoleAssignment: ...
    def list_assignments(self, tenant_id: str) -> list[SubjectRoleAssignment]: ...
    def get_assignment(self, tenant_id: str, assignment_id: str) -> SubjectRoleAssignment | None: ...
    def update_assignment(self, assignment: SubjectRoleAssignment) -> SubjectRoleAssignment: ...
    def create_policy_rule(self, rule: PolicyRule) -> PolicyRule: ...
    def list_policy_rules(self, tenant_id: str) -> list[PolicyRule]: ...
    def get_policy_rule(self, tenant_id: str, rule_id: str) -> PolicyRule | None: ...
    def update_policy_rule(self, rule: PolicyRule) -> PolicyRule: ...
    def log_decision(self, log: AuthorizationDecisionLog) -> None: ...
    def list_decision_logs(self, tenant_id: str) -> list[AuthorizationDecisionLog]: ...


class EventPublisher(Protocol):
    def publish(self, event_type: str, tenant_id: str, payload: dict) -> None: ...


class ObservabilityHook(Protocol):
    def increment(self, metric: str, tags: dict[str, str] | None = None) -> None: ...
